In [169]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np
df = pd.read_csv("../data/social_posts.csv")

In [170]:
df["date"].dtype      # str  ← it's just text like "2026-01-11"

In [171]:
df["date"] = pd.to_datetime(df["date"])
df["date"].dtype      # datetime64

dtype('<M8[us]')

In [172]:
df = pd.read_csv("../data/social_posts.csv", parse_dates=["date"])

In [173]:
pd.to_datetime("03/02/2026").month                      # 3  ← March!
pd.to_datetime("03/02/2026", format="%d/%m/%Y").month   # 2  ← February ✓

3

2

In [174]:
# Bad values: errors="coerce" turns anything unreadable into NaT (“Not a Time”, the date version of NaN) instead of crashing:

In [175]:
pd.to_datetime(pd.Series(["2026-01-05", "oops"]), errors="coerce")
# [2026-01-05, NaT]

0   2026-01-05
1          NaT
dtype: datetime64[us]

In [176]:
df["date"].dt.year          # 2026
df["date"].dt.month         # 1–12
df["date"].dt.day           # 1–31
df["date"].dt.month_name()  # "January"
df["date"].dt.day_name()    # "Sunday"
df["date"].dt.dayofweek     # 0 = Monday … 6 = Sunday
df["date"].dt.quarter       # 1–4

0      2026
1      2026
2      2026
3      2026
4      2026
       ...
295    2026
296    2026
297    2026
298    2026
299    2026
Name: date, Length: 300, dtype: int32

0      1
1      1
2      1
3      1
4      1
      ..
295    6
296    6
297    6
298    6
299    6
Name: date, Length: 300, dtype: int32

0       1
1       2
2       2
3       3
4       4
       ..
295    28
296    28
297    29
298    29
299    29
Name: date, Length: 300, dtype: int32

0      January
1      January
2      January
3      January
4      January
        ...
295       June
296       June
297       June
298       June
299       June
Name: date, Length: 300, dtype: str

0      Thursday
1        Friday
2        Friday
3      Saturday
4        Sunday
         ...
295      Sunday
296      Sunday
297      Monday
298      Monday
299      Monday
Name: date, Length: 300, dtype: str

0      3
1      4
2      4
3      5
4      6
      ..
295    6
296    6
297    0
298    0
299    0
Name: date, Length: 300, dtype: int32

0      1
1      1
2      1
3      1
4      1
      ..
295    2
296    2
297    2
298    2
299    2
Name: date, Length: 300, dtype: int32

In [177]:
df["is_weekend"] = df["date"].dt.dayofweek >= 5

In [178]:
df["month"] = df["date"].dt.month
df.groupby("month")["likes"].mean()

month
1    1473.641509
2    1262.266667
3    1316.147541
4    1314.444444
5    1325.195652
6    1423.700000
Name: likes, dtype: float64

In [179]:
df[df["date"] >= "2026-06-01"]                            # June onwards
df[df["date"].between("2026-03-01", "2026-03-31")]        # all of March (both ends included)

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length,is_weekend,month
250,P0251,2026-06-01,Instagram,UrbanThread,video,40945,3320,119.0,58.0,True,193,False,6
251,P0252,2026-06-01,TikTok,Glowly,video,88589,3883,183.0,33.0,False,157,False,6
252,P0253,2026-06-01,Instagram,Glowly,video,87018,1382,NaN,36.0,False,90,False,6
253,P0254,2026-06-02,Facebook,HomeNest,image,26266,274,11.0,4.0,False,137,False,6
254,P0255,2026-06-03,Facebook,HomeNest,video,27063,202,NaN,3.0,True,173,False,6
255,P0256,2026-06-04,TikTok,UrbanThread,video,42271,1638,65.0,29.0,False,170,False,6
256,P0257,2026-06-05,TikTok,SnackBox,carousel,120039,3174,177.0,37.0,True,277,False,6
257,P0258,2026-06-05,TikTok,HomeNest,video,27956,1874,104.0,11.0,True,375,False,6
258,P0259,2026-06-06,Facebook,UrbanThread,image,43850,137,5.0,3.0,True,62,True,6
259,P0260,2026-06-06,Instagram,HomeNest,carousel,27180,335,19.0,3.0,False,58,True,6
260,P0261,2026-06-08,TikTok,FitFuel,image,63488,470,23.0,4.0,False,371,False,6
261,P0262,2026-06-08,TikTok,UrbanThread,image,41230,1211,25.0,18.0,False,207,False,6
262,P0263,2026-06-08,TikTok,FitFuel,image,62351,388,19.0,7.0,False,23,False,6
263,P0264,2026-06-09,TikTok,UrbanThread,carousel,42432,1907,51.0,51.0,False,291,False,6
264,P0265,2026-06-09,Facebook,UrbanThread,video,42322,152,8.0,4.0,False,374,False,6
265,P0266,2026-06-09,Facebook,Glowly,image,85129,676,36.0,8.0,False,258,False,6
266,P0267,2026-06-10,Facebook,Glowly,image,85529,410,14.0,7.0,False,263,False,6
267,P0268,2026-06-10,Facebook,UrbanThread,image,43895,268,8.0,7.0,False,372,False,6
268,P0269,2026-06-11,TikTok,Glowly,carousel,85410,4440,107.0,122.0,True,222,False,6
269,P0270,2026-06-12,Instagram,FitFuel,carousel,65175,1326,47.0,37.0,True,246,False,6
270,P0271,2026-06-12,TikTok,UrbanThread,video,43217,3384,155.0,88.0,False,23,False,6
271,P0272,2026-06-13,Facebook,UrbanThread,video,41077,421,25.0,4.0,False,312,True,6
272,P0273,2026-06-14,Instagram,SnackBox,video,116490,1258,38.0,17.0,False,334,True,6
273,P0274,2026-06-14,Instagram,FitFuel,image,62115,349,13.0,8.0,False,132,True,6
274,P0275,2026-06-14,Facebook,FitFuel,carousel,65074,318,6.0,8.0,False,160,True,6
275,P0276,2026-06-15,TikTok,FitFuel,video,62006,3435,114.0,25.0,False,141,False,6
276,P0277,2026-06-15,Instagram,SnackBox,image,117336,6133,337.0,107.0,False,89,False,6
277,P0278,2026-06-16,TikTok,FitFuel,video,63303,1976,58.0,38.0,False,70,False,6
278,P0279,2026-06-16,Instagram,Glowly,video,85368,1445,69.0,18.0,False,117,False,6
279,P0280,2026-06-18,Instagram,SnackBox,image,119240,1404,50.0,19.0,True,150,False,6
280,P0281,2026-06-18,Instagram,SnackBox,carousel,124203,1430,71.0,25.0,False,250,False,6
281,P0282,2026-06-18,TikTok,HomeNest,image,27278,406,9.0,10.0,False,393,False,6
282,P0283,2026-06-19,TikTok,FitFuel,image,61814,1280,30.0,18.0,True,243,False,6
283,P0284,2026-06-21,TikTok,UrbanThread,video,41419,2662,130.0,14.0,False,274,True,6
284,P0285,2026-06-21,TikTok,FitFuel,image,63656,1062,23.0,25.0,False,108,True,6
285,P0286,2026-06-22,TikTok,Glowly,image,87294,2534,121.0,41.0,False,89,False,6
286,P0287,2026-06-22,Instagram,HomeNest,carousel,28290,147,4.0,2.0,True,232,False,6
287,P0288,2026-06-22,Instagram,Glowly,video,83574,2116,66.0,30.0,False,181,False,6
288,P0289,2026-06-24,Instagram,UrbanThread,image,40930,225,9.0,6.0,False,312,False,6
289,P0290,2026-06-25,Facebook,Glowly,carousel,83188,558,24.0,5.0,False,186,False,6
290,P0291,2026-06-25,TikTok,SnackBox,carousel,125298,1686,67.0,18.0,False,210,False,6
291,P0292,2026-06-26,Facebook,HomeNest,video,27068,106,6.0,2.0,False,102,False,6
292,P0293,2026-06-26,Facebook,SnackBox,image,121380,188,8.0,2.0,False,329,False,6
293,P0294,2026-06-27,Facebook,FitFuel,video,65997,386,23.0,NaN,False,69,True,6
294,P0295,2026-06-27,TikTok,Glowly,carousel,85903,1969,64.0,23.0,False,360,True,6
295,P0296,2026-06-28,Instagram,UrbanThread,image,42560,234,7.0,6.0,False,221,True,6
296,P0297,2026-06-28,Instagram,HomeNest,image,26391,188,6.0,2.0,True,137,True,6
297,P0298,2026-06-29,Instagram,HomeNest,carousel,26263,321,17.0,2.0,False,298,False,6
298,P0299,2026-06-29,TikTok,SnackBox,image,125910,4107,138.0,113.0,True,171,False,6
299,P0300,2026-06-29,TikTok,FitFuel,image,61646,1990,66.0,57.0,True,162,False,6

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length,is_weekend,month
98,P0099,2026-03-02,Instagram,FitFuel,video,65490,822,31.0,NaN,False,267,False,3
99,P0100,2026-03-03,TikTok,HomeNest,image,28028,1115,NaN,29.0,False,322,False,3
100,P0101,2026-03-03,Instagram,HomeNest,video,27124,203,8.0,2.0,True,48,False,3
101,P0102,2026-03-04,Facebook,Glowly,carousel,83080,731,26.0,11.0,False,334,False,3
102,P0103,2026-03-04,TikTok,SnackBox,carousel,116441,12052,617.0,247.0,False,53,False,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,P0155,2026-03-29,Facebook,UrbanThread,video,43650,644,33.0,19.0,True,22,True,3
155,P0156,2026-03-29,Facebook,UrbanThread,carousel,41705,209,11.0,3.0,False,217,True,3
156,P0157,2026-03-30,Facebook,HomeNest,video,27909,125,3.0,2.0,False,44,False,3
157,P0158,2026-03-31,TikTok,Glowly,image,88860,1000,33.0,15.0,False,284,False,3
158,P0159,2026-03-31,TikTok,HomeNest,carousel,27497,637,37.0,4.0,False,233,False,3

In [180]:
df["date"].max() - df["date"].min()          # Timedelta('179 days')
(df["date"].max() - df["date"].min()).days   # 179  ← plain number

Timedelta('179 days 00:00:00')

179

In [181]:
df["days_since_start"] = (df["date"] - df["date"].min()).dt.days
# one Timedelta	.days
# a column of Timedeltas	.dt.days

In [182]:
weekly = df.set_index("date").resample("W")["post_id"].count()
monthly = df.set_index("date").resample("MS")["likes"].sum()

# "D"	day	the day
# "W"	week	the Sunday the week ends on
# "MS"	month	the 1st of the month

# set_index("date") moves the date column into the index (it returns a new table, as in 2.5). resample then works like groupby: pick a column, pick a function.

# resample vs groupby(df["date"].dt.month):

# resample keeps real dates as labels, so it’s good for trends over time and works across years.
# dt.month gives 1–12, so January 2026 and January 2027 would be merged into one group.

## 2.10 Cheat sheet: Dates

| I want… | Write |
|---|---|
| text → datetime | `pd.to_datetime(df["d"])` |
| convert while reading | `pd.read_csv(..., parse_dates=["d"])` |
| UK format day/month/year | `pd.to_datetime(s, format="%d/%m/%Y")` |
| bad values → NaT | `errors="coerce"` |
| year / month / day | `.dt.year` / `.dt.month` / `.dt.day` |
| names | `.dt.month_name()` / `.dt.day_name()` |
| weekday number (Mon = 0) | `.dt.dayofweek` |
| weekend flag | `.dt.dayofweek >= 5` |
| filter after a date | `df[df["d"] >= "2026-06-01"]` |
| filter a range | `df["d"].between("2026-03-01", "2026-03-31")` |
| gap between two dates | `(d2 - d1).days` |
| gaps for a column | `(df["d"] - df["d"].min()).dt.days` |
| per week / per month | `df.set_index("d").resample("W")["v"].sum()` (`"MS"` for month) |

**Rules**
- Convert first: date tools only work on datetime, not text
- Default reads 03/02 as March 2 (US). Use format= for UK dates
- Column of dates → `.dt` (like `.str` for text)
- resample needs the date as the index

In [183]:
d = pd.Series(["2026-01-05", "2026-01-10", "2026-02-01"])
dt = pd.to_datetime(d)

In [184]:
d.dtype #str
dt.dtype #datetime64

dt.dt.month.tolist() #[1,1,2]

dt.dt.day_name().tolist() #[monday, saturday, sunday]

dt.dt.dayofweek.tolist() #[0, 5, 6]

(dt.dt.dayofweek >= 5).sum() # 2 

(dt.iloc[1] - dt.iloc[0]).days #5

(dt > "2026-01-07").sum() #2

dt.max() - dt.min() #27

pd.to_datetime("03/02/2026").month #3
pd.to_datetime("03/02/2026", format="%d/%m/%Y").month #2

pd.to_datetime(pd.Series(["2026-01-05", "oops"]), errors="coerce").isna().sum() #1

dtype('<M8[us]')

[1, 1, 2]

['Monday', 'Saturday', 'Sunday']

[0, 5, 6]

np.int64(2)

5

np.int64(2)

Timedelta('27 days 00:00:00')

3

2

np.int64(1)

In [185]:
# B1. Convert

# (a) Show the dtype of date before.
df['date'].dtype
# (b) Convert date with pd.to_datetime.
df['date']=pd.to_datetime(df['date'])
# (c) Show the dtype after.
df['date'].dtype
# (d) First and last date (.min(), .max()).
df['date'].min(), df['date'].max()
# (e) How many days does the data cover? Give a plain number.
(df['date'].max() - df['date'].min()).days

dtype('<M8[us]')

dtype('<M8[us]')

(Timestamp('2026-01-01 00:00:00'), Timestamp('2026-06-29 00:00:00'))

179

In [186]:
# B2. Month

# (a) Make month = month number.
df['month']= df['date'].dt.month
# (b) Posts per month (.size()).
df.groupby('month').size()
# (c) Mean likes per month, rounded to 1.
df.groupby('month')['likes'].mean().round(1)
# (d) Comment: which month had the most posts? Which had the highest mean likes?
#March, January

month
1    53
2    45
3    61
4    45
5    46
6    50
dtype: int64

month
1    1473.6
2    1262.3
3    1316.1
4    1314.4
5    1325.2
6    1423.7
Name: likes, dtype: float64

In [187]:
# B3. Weekday

# (a) Make weekday = day name.
df['weekday']= df['date'].dt.day_name()
# (b) Mean likes per weekday, rounded to 1, sorted highest first.
df.groupby('weekday')['likes'].mean().round(1).sort_values(ascending=False)
# (c) Comment: best and worst day to post?
#best: Wed, worst: Sat

weekday
Wednesday    1705.8
Monday       1674.2
Sunday       1399.0
Friday       1301.1
Thursday     1179.0
Tuesday      1150.8
Saturday     1058.6
Name: likes, dtype: float64

In [188]:
# B4. Weekend

# (a) Make is_weekend (True for Sat/Sun).
df['is_weekend']= df['date'].dt.dayofweek >= 5
# (b) How many weekend posts?
df['is_weekend'].sum()
# (c) Mean likes, weekend vs weekday, rounded to 1.
df.groupby('is_weekend')['likes'].mean().round(1)
# (d) Comment: does weekend posting help? (Compare with B3: is it the same story for both weekend days?)
#On the surface it doesn't help-- mean likes lower on weekend. B3 indicated same--Sat was the worst day for posting. However, Sunday is better than most weekdays, meaning weekend avg is dragged down by saturday.

np.int64(90)

is_weekend
False    1417.1
True     1209.9
Name: likes, dtype: float64

In [189]:
# B5. Filtering

# (a) How many posts are in March? Do it two ways: with & and >= / <, and with .between.
((df['date']>='2026-03-01') & (df['date']<'2026-04-01')).sum()
df[df['date'].between('2026-03-01', '2026-03-31')]
# (b) How many posts are from 1 June onwards?
(df['date']>='2026-06-01').sum()

np.int64(61)

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length,is_weekend,month,days_since_start,weekday
98,P0099,2026-03-02,Instagram,FitFuel,video,65490,822,31.0,NaN,False,267,False,3,60,Monday
99,P0100,2026-03-03,TikTok,HomeNest,image,28028,1115,NaN,29.0,False,322,False,3,61,Tuesday
100,P0101,2026-03-03,Instagram,HomeNest,video,27124,203,8.0,2.0,True,48,False,3,61,Tuesday
101,P0102,2026-03-04,Facebook,Glowly,carousel,83080,731,26.0,11.0,False,334,False,3,62,Wednesday
102,P0103,2026-03-04,TikTok,SnackBox,carousel,116441,12052,617.0,247.0,False,53,False,3,62,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,P0155,2026-03-29,Facebook,UrbanThread,video,43650,644,33.0,19.0,True,22,True,3,87,Sunday
155,P0156,2026-03-29,Facebook,UrbanThread,carousel,41705,209,11.0,3.0,False,217,True,3,87,Sunday
156,P0157,2026-03-30,Facebook,HomeNest,video,27909,125,3.0,2.0,False,44,False,3,88,Monday
157,P0158,2026-03-31,TikTok,Glowly,image,88860,1000,33.0,15.0,False,284,False,3,89,Tuesday
158,P0159,2026-03-31,TikTok,HomeNest,carousel,27497,637,37.0,4.0,False,233,False,3,89,Tuesday

np.int64(50)

In [190]:
# B6. Days since start

# (a) Make days_since_start = days since the first post (a plain number).
df['days_since_start']= (df['date']-df['date'].min()).dt.days
# (b) What’s its max?
df['days_since_start'].max()
# (c) How many days after the start was the viral post P0019? (Use .loc with a mask, 2.4.)
df.loc[df['post_id']=='P0019', ['days_since_start']]

np.int64(179)

    days_since_start
18                10

In [191]:
# B7. Weekly posts (resample)

# (a) Posts per week with resample("W") and post_id count.
weekly= df.set_index("date").resample("W")["post_id"].count()
weekly
# (b) How many weeks are there?
len(weekly)
weekly.count()
# weekly.count() works, but len(weekly) is clearer. count skips NaN, so it could undercount weeks with missing values.

# (c) Which week had the most posts? Use idxmax() (2.6).
weekly.idxmax()
# (d) How many posts were in that week?
weekly['2026-03-15 00:00:00']
# (e) Comment: the first week has far fewer posts. Why? (Hint: check what day 1 Jan 2026 was, and what date the first week’s label is.)
#only 4 days since 1st Jan so doesn't count the full 7 days-only thurs till sunday

date
2026-01-04     6
2026-01-11    13
2026-01-18    13
2026-01-25    12
2026-02-01    10
2026-02-08     8
2026-02-15    10
2026-02-22    15
2026-03-01    11
2026-03-08    14
2026-03-15    16
2026-03-22    15
2026-03-29    13
2026-04-05     9
2026-04-12    10
2026-04-19    13
2026-04-26    13
2026-05-03     7
2026-05-10    12
2026-05-17    10
2026-05-24    10
2026-05-31    10
2026-06-07    10
2026-06-14    15
2026-06-21    10
2026-06-28    12
2026-07-05     3
Freq: W-SUN, Name: post_id, dtype: int64

27

np.int64(27)

Timestamp('2026-03-15 00:00:00')

np.int64(16)

In [192]:
# B8. Monthly likes (resample)

# (a) Total likes per month with resample("MS").
monthly= df.set_index("date").resample("MS")["likes"].sum()
monthly

# (b) Comment: compare to B2. Why do totals and means rank months differently? (Hint: B2(b).)
#march has more ports overall so more likes. january has more likes/no. of posts which means better stats

date
2026-01-01    78103
2026-02-01    56802
2026-03-01    80285
2026-04-01    59150
2026-05-01    60959
2026-06-01    71185
Freq: MS, Name: likes, dtype: int64

In [193]:
uk = pd.Series(["03/02/2026", "15/02/2026", "2026-02-20", "not a date"])

# (a) Convert with format="%d/%m/%Y" and errors="coerce".
pd.to_datetime(uk, format="%d/%m/%Y", errors="coerce") 
# (b) How many NaT?
#2
# (c) Comment: "2026-02-20" is a perfectly good date. Why did it become NaT?
#not is specified format. it's in ymd

0   2026-02-03
1   2026-02-15
2          NaT
3          NaT
dtype: datetime64[us]

In [194]:
raw = pd.read_csv("../data/social_posts.csv")
raw['date']=pd.to_datetime(raw['date'])
raw["date"].dt.month  #date is not yet read as date/time

0      1
1      1
2      1
3      1
4      1
      ..
295    6
296    6
297    6
298    6
299    6
Name: date, Length: 300, dtype: int32

In [195]:
df.set_index("date").resample("W")["likes"].sum()
#index not set

date
2026-01-04     7873
2026-01-11    26487
2026-01-18    16954
2026-01-25    18397
2026-02-01    11384
2026-02-08     7135
2026-02-15    17487
2026-02-22    22131
2026-03-01     7057
2026-03-08    22547
2026-03-15    24579
2026-03-22    21710
2026-03-29     9687
2026-04-05    12571
2026-04-12     7022
2026-04-19    13256
2026-04-26    25734
2026-05-03     4928
2026-05-10    10181
2026-05-17    16125
2026-05-24    19866
2026-05-31    12188
2026-06-07    16219
2026-06-14    16978
2026-06-21    21233
2026-06-28    10337
2026-07-05     6418
Freq: W-SUN, Name: likes, dtype: int64

In [196]:
pd.to_datetime("05/03/2026", format="%d/%m/%Y").month
#reads as usa date

3

In [197]:
# ((df['date'].dt.dayofweek== 6) & (df['date'].dt.month==6)).sum()