In [187]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np
df = pd.read_csv("../data/social_posts.csv")
brands = pd.read_csv("../data/brands.csv")

In [188]:
top_tiktok = (
    df
    .query("platform == 'TikTok'")
    .assign(eng=lambda d: d["likes"] + d["comments"].fillna(0) + d["shares"].fillna(0))
    .sort_values("eng", ascending=False)
    [["post_id", "brand", "eng"]]
    .head(5)
)

In [189]:
# result = (
#     df
#     .step_one()
#     .step_two()
# )

In [190]:
(
    # df
    # .query("platform == 'TikTok'")
    # .assign(...)
    # .sort_values(...)
)
# Debugging tip: comment out the later lines to check the output of each step:

()

In [191]:
# .query(): filter with a readable string
df.query("likes > 5000")
df.query("platform == 'TikTok' and likes > 5000")
df.query("platform in ['Instagram', 'Facebook']")

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length
18,P0019,2026-01-11,TikTok,SnackBox,video,124109,13577,273.0,261.0,False,359
42,P0043,2026-01-24,TikTok,Glowly,video,85427,5056,288.0,54.0,False,355
70,P0071,2026-02-15,TikTok,SnackBox,carousel,122504,5454,262.0,162.0,False,276
74,P0075,2026-02-18,TikTok,SnackBox,video,116576,5632,285.0,156.0,False,399
102,P0103,2026-03-04,TikTok,SnackBox,carousel,116441,12052,617.0,247.0,False,53
128,P0129,2026-03-16,TikTok,SnackBox,video,123105,9030,418.0,165.0,False,311
200,P0201,2026-04-26,Instagram,SnackBox,image,125213,5198,258.0,112.0,False,252
209,P0210,2026-05-06,TikTok,Glowly,video,83481,5761,177.0,77.0,False,300
229,P0230,2026-05-16,TikTok,SnackBox,carousel,116738,5485,247.0,138.0,False,176
239,P0240,2026-05-22,Instagram,Glowly,video,85497,5233,311.0,95.0,False,319
276,P0277,2026-06-15,Instagram,SnackBox,image,117336,6133,337.0,107.0,False,89

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length
18,P0019,2026-01-11,TikTok,SnackBox,video,124109,13577,273.0,261.0,False,359
42,P0043,2026-01-24,TikTok,Glowly,video,85427,5056,288.0,54.0,False,355
70,P0071,2026-02-15,TikTok,SnackBox,carousel,122504,5454,262.0,162.0,False,276
74,P0075,2026-02-18,TikTok,SnackBox,video,116576,5632,285.0,156.0,False,399
102,P0103,2026-03-04,TikTok,SnackBox,carousel,116441,12052,617.0,247.0,False,53
128,P0129,2026-03-16,TikTok,SnackBox,video,123105,9030,418.0,165.0,False,311
209,P0210,2026-05-06,TikTok,Glowly,video,83481,5761,177.0,77.0,False,300
229,P0230,2026-05-16,TikTok,SnackBox,carousel,116738,5485,247.0,138.0,False,176

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length
0,P0001,2026-01-01,Instagram,Glowly,image,82837,631,34.0,16.0,False,158
2,P0003,2026-01-02,Instagram,FitFuel,video,61341,3158,88.0,52.0,False,277
3,P0004,2026-01-03,Instagram,SnackBox,image,118210,1612,75.0,27.0,False,236
5,P0006,2026-01-04,Instagram,FitFuel,image,65629,600,29.0,7.0,False,223
6,P0007,2026-01-06,Instagram,Glowly,image,85365,1415,54.0,26.0,False,59
...,...,...,...,...,...,...,...,...,...,...,...
292,P0293,2026-06-26,Facebook,SnackBox,image,121380,188,8.0,2.0,False,329
293,P0294,2026-06-27,Facebook,FitFuel,video,65997,386,23.0,NaN,False,69
295,P0296,2026-06-28,Instagram,UrbanThread,image,42560,234,7.0,6.0,False,221
296,P0297,2026-06-28,Instagram,HomeNest,image,26391,188,6.0,2.0,True,137
297,P0298,2026-06-29,Instagram,HomeNest,carousel,26263,321,17.0,2.0,False,298

In [192]:
threshold = 5000
df.query("likes > @threshold")

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length
18,P0019,2026-01-11,TikTok,SnackBox,video,124109,13577,273.0,261.0,False,359
42,P0043,2026-01-24,TikTok,Glowly,video,85427,5056,288.0,54.0,False,355
70,P0071,2026-02-15,TikTok,SnackBox,carousel,122504,5454,262.0,162.0,False,276
74,P0075,2026-02-18,TikTok,SnackBox,video,116576,5632,285.0,156.0,False,399
102,P0103,2026-03-04,TikTok,SnackBox,carousel,116441,12052,617.0,247.0,False,53
128,P0129,2026-03-16,TikTok,SnackBox,video,123105,9030,418.0,165.0,False,311
200,P0201,2026-04-26,Instagram,SnackBox,image,125213,5198,258.0,112.0,False,252
209,P0210,2026-05-06,TikTok,Glowly,video,83481,5761,177.0,77.0,False,300
229,P0230,2026-05-16,TikTok,SnackBox,carousel,116738,5485,247.0,138.0,False,176
239,P0240,2026-05-22,Instagram,Glowly,video,85497,5233,311.0,95.0,False,319
276,P0277,2026-06-15,Instagram,SnackBox,image,117336,6133,337.0,107.0,False,89

In [193]:
# df[(df["a"] > 5) & (df["b"] == "x")]	
# df.query("a > 5 and b == 'x'")

In [194]:
# .assign(): add columns inside a chain
df.assign(likes_k=lambda d: d["likes"] / 1000)

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length,likes_k
0,P0001,2026-01-01,Instagram,Glowly,image,82837,631,34.0,16.0,False,158,0.631
1,P0002,2026-01-02,TikTok,HomeNest,image,27506,485,12.0,12.0,False,311,0.485
2,P0003,2026-01-02,Instagram,FitFuel,video,61341,3158,88.0,52.0,False,277,3.158
3,P0004,2026-01-03,Instagram,SnackBox,image,118210,1612,75.0,27.0,False,236,1.612
4,P0005,2026-01-04,TikTok,SnackBox,image,122826,1387,70.0,15.0,False,121,1.387
...,...,...,...,...,...,...,...,...,...,...,...,...
295,P0296,2026-06-28,Instagram,UrbanThread,image,42560,234,7.0,6.0,False,221,0.234
296,P0297,2026-06-28,Instagram,HomeNest,image,26391,188,6.0,2.0,True,137,0.188
297,P0298,2026-06-29,Instagram,HomeNest,carousel,26263,321,17.0,2.0,False,298,0.321
298,P0299,2026-06-29,TikTok,SnackBox,image,125910,4107,138.0,113.0,True,171,4.107
299,P0300,2026-06-29,TikTok,FitFuel,image,61646,1990,66.0,57.0,True,162,1.990

In [195]:
df.assign(
    eng=lambda d: d["likes"] + d["comments"].fillna(0) + d["shares"].fillna(0),
    eng_rate=lambda d: d["eng"] / d["followers"] * 100,     # uses eng from the line above
)

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length,eng,eng_rate
0,P0001,2026-01-01,Instagram,Glowly,image,82837,631,34.0,16.0,False,158,681.0,0.822096
1,P0002,2026-01-02,TikTok,HomeNest,image,27506,485,12.0,12.0,False,311,509.0,1.850505
2,P0003,2026-01-02,Instagram,FitFuel,video,61341,3158,88.0,52.0,False,277,3298.0,5.376502
3,P0004,2026-01-03,Instagram,SnackBox,image,118210,1612,75.0,27.0,False,236,1714.0,1.449962
4,P0005,2026-01-04,TikTok,SnackBox,image,122826,1387,70.0,15.0,False,121,1472.0,1.198443
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,P0296,2026-06-28,Instagram,UrbanThread,image,42560,234,7.0,6.0,False,221,247.0,0.580357
296,P0297,2026-06-28,Instagram,HomeNest,image,26391,188,6.0,2.0,True,137,196.0,0.742677
297,P0298,2026-06-29,Instagram,HomeNest,carousel,26263,321,17.0,2.0,False,298,340.0,1.294597
298,P0299,2026-06-29,TikTok,SnackBox,image,125910,4107,138.0,113.0,True,171,4358.0,3.461202
299,P0300,2026-06-29,TikTok,FitFuel,image,61646,1990,66.0,57.0,True,162,2113.0,3.427635

In [196]:
# .pipe(): plug your own function into the chain
def add_eng(d):
    d = d.copy()
    d["eng"] = d["likes"] + d["comments"].fillna(0) + d["shares"].fillna(0)
    return d

df.pipe(add_eng)          # same as add_eng(df), but fits in a chain

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length,eng
0,P0001,2026-01-01,Instagram,Glowly,image,82837,631,34.0,16.0,False,158,681.0
1,P0002,2026-01-02,TikTok,HomeNest,image,27506,485,12.0,12.0,False,311,509.0
2,P0003,2026-01-02,Instagram,FitFuel,video,61341,3158,88.0,52.0,False,277,3298.0
3,P0004,2026-01-03,Instagram,SnackBox,image,118210,1612,75.0,27.0,False,236,1714.0
4,P0005,2026-01-04,TikTok,SnackBox,image,122826,1387,70.0,15.0,False,121,1472.0
...,...,...,...,...,...,...,...,...,...,...,...,...
295,P0296,2026-06-28,Instagram,UrbanThread,image,42560,234,7.0,6.0,False,221,247.0
296,P0297,2026-06-28,Instagram,HomeNest,image,26391,188,6.0,2.0,True,137,196.0
297,P0298,2026-06-29,Instagram,HomeNest,carousel,26263,321,17.0,2.0,False,298,340.0
298,P0299,2026-06-29,TikTok,SnackBox,image,125910,4107,138.0,113.0,True,171,4358.0
299,P0300,2026-06-29,TikTok,FitFuel,image,61646,1990,66.0,57.0,True,162,2113.0

In [197]:
def load_posts(path):
    return (
        pd.read_csv(path, parse_dates=["date"])
        .assign(
            eng=lambda d: d["likes"] + d["comments"].fillna(0) + d["shares"].fillna(0),
            month=lambda d: d["date"].dt.month,
        )
    )

posts = load_posts("../data/social_posts.csv")

When NOT to chain
Chains longer than ~10 steps get hard to read. Split them into a function plus a chain.
If you need to look at the data between steps (exploring), step-by-step cells are fine. Chain the final version.

## 2.12 Cheat sheet: Method chaining

| I want… | Write |
|---|---|
| multi-line chain | wrap in `( ... )`, one `.step()` per line |
| filter in a chain | `.query("a > 5 and b == 'x'")` |
| filter by list | `.query("b in ['x', 'y']")` |
| use a Python variable | `.query("a > @threshold")` |
| add a column in a chain | `.assign(new=lambda d: d["a"] * 2)` |
| column using another new one | same `.assign`, later line uses the earlier name |
| custom step | `.pipe(my_function)` (function returns a DataFrame) |
| debug a chain | comment out later lines |
| reusable cleaning | `def load(path): return (pd.read_csv(path) .assign(...) ...)` |

**Rules**
- No outer brackets → SyntaxError on the next line
- query: `and`/`or` + quotes inside; masks: `&`/`|` + brackets
- lambda d = the table at this point in the chain
- Raw data is never modified → re-runnable, no stale state

In [198]:
toy = pd.DataFrame({"name": ["a", "b", "c", "d"], "score": [5, 12, 8, 20], "team": ["x", "y", "x", "y"]})
toy

  name  score team
0    a      5    x
1    b     12    y
2    c      8    x
3    d     20    y

In [199]:
toy.query("score > 6").shape #3,3
toy.query("team == 'x' and score > 6")["name"].tolist() #[c]
limit = 10
toy.query("score > @limit")["name"].tolist() #[b, d]
toy.assign(double=lambda d: d["score"] * 2)["double"].sum() #90
toy.shape #4,3 , no
toy.assign(a=lambda d: d["score"] + 1, 
           b=lambda d: d["a"] * 10)["b"].tolist() #[60, 130, 90, 210]

(3, 3)

['c']

['b', 'd']

np.int64(90)

(4, 3)

[60, 130, 90, 210]

In [200]:
(toy
    .query("team == 'y'")
    .assign(pct=lambda d: d["score"] / d["score"].sum())
    ["pct"].tolist())

# [.375, .625]

[0.375, 0.625]

In [201]:
toy.query("team in ['x']").shape #2,3

(2, 3)

In [202]:
def plus_one(d): 
    d = d.copy() 
    d["score"] = d["score"] + 1 
    
toy.pipe(plus_one)
#nothing, no return means the function returns nothing

In [203]:
#    r = toy
#        .query("score > 6")
# #error

In [204]:
# t = df.copy()
# t = t[t["platform"] == "TikTok"]
# t["eng"] = t["likes"] + t["comments"].fillna(0) + t["shares"].fillna(0)
# t = t.sort_values("eng", ascending=False)
# t = t[["post_id", "brand", "eng"]].head(5)

top_tiktok= (
    df
    .query("platform=='TikTok'")
    .assign(eng=lambda d: d["likes"] + d["comments"].fillna(0) + d["shares"].fillna(0))
    .sort_values('eng', ascending = False) 
    [["post_id", "brand", "eng"]]
    .head(5)    
)

top_tiktok, df.shape, "eng" in df.columns

(    post_id     brand      eng
 18    P0019  SnackBox  14111.0
 102   P0103  SnackBox  12916.0
 128   P0129  SnackBox   9613.0
 74    P0075  SnackBox   6073.0
 209   P0210    Glowly   6015.0,
 (300, 11),
 False)

In [205]:
# B2. query practice

# (a) Count Instagram videos with more than 2000 likes using query.
(
    t
    .query('platform == "Instagram" and likes > 2000 and post_type == "video"').shape[0]
)
# (b) Make threshold = 5000 and count posts above it using @threshold.
threshold = 5000
(
    t
    .query('likes>@threshold').shape[0]
)
# (c) Count posts on Instagram or Facebook using in [...].
(
    t
    .query("platform in ['Instagram', 'Facebook']").shape[0]
)

13

11

196

In [206]:
# B3. assign with two columns

# (a) One chain:
# assign eng (likes + comments + shares, missing → 0)
(
    t
    .assign(eng=lambda d: d['likes']+d['comments'].fillna(0)+d['shares'].fillna(0),
           eng_rate= lambda d: d['eng']/d['followers']*100)
    .groupby('brand')['eng_rate'].mean()
    .round(2)
    .sort_values(ascending=False)
)
# and eng_rate = eng / followers × 100 (in the same assign)
# groupby brand → mean eng_rate
# round to 2
# sort highest first
# (b) Comment: compare to 2.6 B7. UrbanThread is slightly different. Why? (Hint: what happened to rows with missing comments/shares then vs now?)
#missing became 0, so were included in mean--NaNs are otherwise excluded

brand
SnackBox       2.36
UrbanThread    2.11
Glowly         2.03
FitFuel        1.96
HomeNest       1.78
Name: eng_rate, dtype: float64

In [207]:
# B4. pipe

# (a) Write add_eng(d). It returns a copy with an eng column.
def add_eng(df):
    d= df.copy()
    d["eng"] = d["likes"] + d["comments"].fillna(0) + d["shares"].fillna(0)
    return d
# (b) Use it in a chain: df.pipe(add_eng), then eng total.
df.pipe(add_eng)
df.pipe(add_eng)['eng'].sum()
# (c) Comment: what would happen if add_eng had no return?
#None is handed back

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length,eng
0,P0001,2026-01-01,Instagram,Glowly,image,82837,631,34.0,16.0,False,158,681.0
1,P0002,2026-01-02,TikTok,HomeNest,image,27506,485,12.0,12.0,False,311,509.0
2,P0003,2026-01-02,Instagram,FitFuel,video,61341,3158,88.0,52.0,False,277,3298.0
3,P0004,2026-01-03,Instagram,SnackBox,image,118210,1612,75.0,27.0,False,236,1714.0
4,P0005,2026-01-04,TikTok,SnackBox,image,122826,1387,70.0,15.0,False,121,1472.0
...,...,...,...,...,...,...,...,...,...,...,...,...
295,P0296,2026-06-28,Instagram,UrbanThread,image,42560,234,7.0,6.0,False,221,247.0
296,P0297,2026-06-28,Instagram,HomeNest,image,26391,188,6.0,2.0,True,137,196.0
297,P0298,2026-06-29,Instagram,HomeNest,carousel,26263,321,17.0,2.0,False,298,340.0
298,P0299,2026-06-29,TikTok,SnackBox,image,125910,4107,138.0,113.0,True,171,4358.0
299,P0300,2026-06-29,TikTok,FitFuel,image,61646,1990,66.0,57.0,True,162,2113.0

np.float64(429666.0)

In [208]:
# B5. A cleaning function for influencers (uses 2.9 and 2.11)
def load_posts(path):
    return (
        pd.read_csv(path, parse_dates=["date"])
        .assign(
            eng=lambda d: d["likes"] + d["comments"].fillna(0) + d["shares"].fillna(0),
            month=lambda d: d["date"].dt.month,
        )
    )

posts = load_posts("../data/social_posts.csv")

# (a) Write clean_inf(path) that returns one chain:

def clean_inf(path):
    return (
        pd.read_csv(path, na_values=["-", "unknown"])
            
        .assign(followers= lambda d: d['followers_raw'].str.replace(",", "").astype(float), 
                verified_bool=lambda d: d['verified'].str.lower().map({"yes": True, "no": False}),
                rate= lambda d: d['rate_raw'].str.replace(r"\$", "", regex=True).astype(float),
                country= lambda d: d['country'].fillna('Unknown'),
                tier= lambda d: pd.Categorical(d['tier'],
                                               categories=["bronze", "silver", "gold", "platinum"],
                                               ordered=True),
                likes_was_missing= lambda d: d['avg_likes'].isna(),
                avg_likes= lambda d: d['avg_likes'].fillna(d.groupby('tier', observed=True)['avg_likes'].transform("median")))
        .drop(columns= ['followers_raw', 'rate_raw', 'verified'])
            )                    
# read with na_values=["-", "unknown"]
# assign followers (commas removed → float)            
# assign rate ($ removed → float)
# assign verified_bool (lower → map)
# assign country filled with "Unknown"
# assign tier as an ordered category
# assign likes_was_missing flag
# assign avg_likes filled with the tier median (transform). Order matters: the flag must come before the fill.
# drop followers_raw, rate_raw and verified

# (b) inf = clean_inf("../data/influencers.csv")
inf = clean_inf("../data/influencers.csv")
# (c) Show inf.dtypes and inf.isna().sum().
inf.dtypes
inf.isna().sum()
# (d) Median rate per tier (observed=True).
(
    inf
    .groupby("tier", observed=True)["rate"]
    .median()
)
# (e) Re-run proof: call clean_inf again into inf2, and show that inf.equals(inf2) is True.
inf2= clean_inf("../data/influencers.csv")
inf.equals(inf2)

handle                    str
niche                     str
tier                 category
country                   str
avg_likes             float64
followers             float64
verified_bool          object
rate                  float64
likes_was_missing        bool
dtype: object

handle               0
niche                0
tier                 0
country              0
avg_likes            0
followers            3
verified_bool        2
rate                 3
likes_was_missing    0
dtype: int64

tier
bronze        50.0
silver       220.0
gold        1080.0
platinum    3890.0
Name: rate, dtype: float64

True

In [209]:
# B6. Merge in a chain (uses 2.7)
df = pd.read_csv("../data/social_posts.csv")
brands = pd.read_csv("../data/brands.csv")
df.head(2)
# (a) One chain:
(
    df
    .merge(brands, on='brand', how='left')
    .dropna(subset=['category'])
    .groupby('category')['likes'].mean()
    .round(1)
    .sort_values(ascending=False)
    
)
# df → left merge with brands
# drop rows with no category (dropna(subset=[...]))
# groupby category → mean likes
# round to 1
# sort highest first

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length
0,P0001,2026-01-01,Instagram,Glowly,image,82837,631,34.0,16.0,False,158
1,P0002,2026-01-02,TikTok,HomeNest,image,27506,485,12.0,12.0,False,311

category
food       2688.8
beauty     1639.6
fitness    1179.4
fashion     841.9
Name: likes, dtype: float64

In [210]:
# B7. Dates in a chain (uses 2.10)

# (a) One chain:
(
    df
    .assign(date= lambda d: pd.to_datetime(d['date']),
            month= lambda d: d['date'].dt.month)
    .groupby('month').size()
)


(
    df
    .assign(date= lambda d: pd.to_datetime(d['date']))
    .set_index('date')
    .resample('MS')['likes']
    .sum()
)     
# df → assign date converted with pd.to_datetime
# assign month = month number
# groupby month → size()
# (b) A second chain: df → convert date → set_index("date") → resample("MS") → likes sum.

month
1    53
2    45
3    61
4    45
5    46
6    50
dtype: int64

date
2026-01-01    78103
2026-02-01    56802
2026-03-01    80285
2026-04-01    59150
2026-05-01    60959
2026-06-01    71185
Freq: MS, Name: likes, dtype: int64

In [211]:
result = (
    df
    .query("likes > 1000")
    .head()
)
#opening/closing brackets missing

In [212]:
(df
 .assign(eng=lambda d: d["likes"] + d["comments"].fillna(0))
 .assign(eng_k= lambda d: d["eng"] / 1000))

# eng_k = lambda not defined, and d called df

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length,eng,eng_k
0,P0001,2026-01-01,Instagram,Glowly,image,82837,631,34.0,16.0,False,158,665.0,0.665
1,P0002,2026-01-02,TikTok,HomeNest,image,27506,485,12.0,12.0,False,311,497.0,0.497
2,P0003,2026-01-02,Instagram,FitFuel,video,61341,3158,88.0,52.0,False,277,3246.0,3.246
3,P0004,2026-01-03,Instagram,SnackBox,image,118210,1612,75.0,27.0,False,236,1687.0,1.687
4,P0005,2026-01-04,TikTok,SnackBox,image,122826,1387,70.0,15.0,False,121,1457.0,1.457
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,P0296,2026-06-28,Instagram,UrbanThread,image,42560,234,7.0,6.0,False,221,241.0,0.241
296,P0297,2026-06-28,Instagram,HomeNest,image,26391,188,6.0,2.0,True,137,194.0,0.194
297,P0298,2026-06-29,Instagram,HomeNest,carousel,26263,321,17.0,2.0,False,298,338.0,0.338
298,P0299,2026-06-29,TikTok,SnackBox,image,125910,4107,138.0,113.0,True,171,4245.0,4.245
299,P0300,2026-06-29,TikTok,FitFuel,image,61646,1990,66.0,57.0,True,162,2056.0,2.056

In [213]:
cutoff = 3000
df.query("likes >@ cutoff")
# @missing

,post_id,date,platform,brand,post_type,followers,likes,comments,shares,sponsored,caption_length
2,P0003,2026-01-02,Instagram,FitFuel,video,61341,3158,88.0,52.0,False,277
18,P0019,2026-01-11,TikTok,SnackBox,video,124109,13577,273.0,261.0,False,359
26,P0027,2026-01-16,Instagram,SnackBox,video,120454,3958,104.0,23.0,False,295
40,P0041,2026-01-24,TikTok,SnackBox,video,125479,4401,115.0,40.0,False,388
42,P0043,2026-01-24,TikTok,Glowly,video,85427,5056,288.0,54.0,False,355
61,P0062,2026-02-08,TikTok,Glowly,carousel,88693,3550,137.0,35.0,False,311
70,P0071,2026-02-15,TikTok,SnackBox,carousel,122504,5454,262.0,162.0,False,276
74,P0075,2026-02-18,TikTok,SnackBox,video,116576,5632,285.0,156.0,False,399
75,P0076,2026-02-18,TikTok,SnackBox,image,118825,4884,163.0,109.0,False,219
102,P0103,2026-03-04,TikTok,SnackBox,carousel,116441,12052,617.0,247.0,False,53
121,P0122,2026-03-12,TikTok,SnackBox,image,123649,3626,115.0,100.0,False,232
122,P0123,2026-03-12,TikTok,Glowly,carousel,84561,3993,183.0,98.0,False,279
128,P0129,2026-03-16,TikTok,SnackBox,video,123105,9030,418.0,165.0,False,311
136,P0137,2026-03-20,TikTok,SnackBox,carousel,123406,3478,184.0,27.0,True,64
159,P0160,2026-04-01,Instagram,SnackBox,video,118324,4927,173.0,95.0,False,94
189,P0190,2026-04-20,TikTok,FitFuel,video,61744,4970,139.0,128.0,False,144
192,P0193,2026-04-21,Instagram,SnackBox,video,124821,3572,99.0,75.0,False,187
200,P0201,2026-04-26,Instagram,SnackBox,image,125213,5198,258.0,112.0,False,252
209,P0210,2026-05-06,TikTok,Glowly,video,83481,5761,177.0,77.0,False,300
229,P0230,2026-05-16,TikTok,SnackBox,carousel,116738,5485,247.0,138.0,False,176
232,P0233,2026-05-18,Instagram,Glowly,video,84359,4315,228.0,80.0,True,387
238,P0239,2026-05-22,TikTok,SnackBox,carousel,119979,3254,129.0,40.0,True,102
239,P0240,2026-05-22,Instagram,Glowly,video,85497,5233,311.0,95.0,False,319
250,P0251,2026-06-01,Instagram,UrbanThread,video,40945,3320,119.0,58.0,True,193
251,P0252,2026-06-01,TikTok,Glowly,video,88589,3883,183.0,33.0,False,157
256,P0257,2026-06-05,TikTok,SnackBox,carousel,120039,3174,177.0,37.0,True,277
268,P0269,2026-06-11,TikTok,Glowly,carousel,85410,4440,107.0,122.0,True,222
270,P0271,2026-06-12,TikTok,UrbanThread,video,43217,3384,155.0,88.0,False,23
275,P0276,2026-06-15,TikTok,FitFuel,video,62006,3435,114.0,25.0,False,141
276,P0277,2026-06-15,Instagram,SnackBox,image,117336,6133,337.0,107.0,False,89
298,P0299,2026-06-29,TikTok,SnackBox,image,125910,4107,138.0,113.0,True,171

In [214]:
# df= pd.read_csv("../data/social_posts.csv")
# min_likes = 2000
# (
#     df
#     .query('likes>@min_likes')
#     .assign(eng= lambda d: d["likes"].fillna(0) + d["comments"].fillna(0) + d["shares"].fillna(0))
#     .groupby('platform')['eng'].mean()
#     .round(0)
# )

platform
Facebook     2400.0
Instagram    3595.0
TikTok       4518.0
Name: eng, dtype: float64

In [215]:
# def load_comments(path):
#     return(
#         pd.read_csv(path)
#         .assign(brand= lambda d: d['brand_raw'].str.strip().str.lower(),
#         has_text= lambda d: d['text'].notna())
#         .drop(columns= 'brand_raw')
#     )

# df= load_comments("../data/comments_raw.csv")
# df

,comment_id,post_id,user,text,price_raw,brand,has_text
0,C001,P0037,@gabi_x,Is this vegan?,£8,glowly,True
1,C002,P0066,@hana,LOVE the new flavour #snacktime,NaN,urbanthread,True
2,C003,P0137,@ben.t,Refund please. Wrong size.,£8,fitfuel,True
3,C004,P0024,@gabi_x,Price is too high tbh,NaN,snackbox,True
4,C005,P0088,@finn,NaN,NaN,glowly,False
5,C006,P0004,@hana,love love love,NaN,homenest,True
6,C007,P0175,@jo.l,meh,NaN,snackbox,True
7,C008,P0172,@ben.t,Love it #fitfam,NaN,glowly,True
8,C009,P0135,@chloe99,how much is this?,NaN,fitfuel,True
9,C010,P0015,@hana,how much is this?,NaN,glowly,True
10,C011,P0179,@dev_m,how much is this?,$12.99,glowly,True
11,C012,P0093,@hana,Is this vegan?,NaN,snack box,True
12,C013,P0118,@dev_m,"great quality, fast delivery",$12.99,glowly,True
13,C014,P0270,@finn,"great quality, fast delivery",NaN,homenest,True
14,C015,P0244,@chloe99,love love love,$9.50,snackbox,True
15,C016,P0167,@hana,Love this!! #obsessed,£22.00,fitfuel,True
16,C017,P0229,@chloe99,NaN,NaN,fitfuel,False
17,C018,P0005,@gabi_x,Best purchase this year,$120,homenest,True
18,C019,P0048,@finn,Love it #fitfam,NaN,glowly,True
19,C020,P0048,@ivan_p,NaN,$9.50,glowly,False
20,C021,P0048,@jo.l,Where can I buy this? price?,"$1,050.00",fitfuel,True
21,C022,P0210,@jo.l,Best purchase this year,NaN,fitfuel,True
22,C023,P0102,@ivan_p,Where can I buy this? price?,NaN,glowly,True
23,C024,P0191,@hana,can you ship to Canada?,NaN,homenest,True
24,C025,P0248,@ben.t,"great quality, fast delivery",NaN,fitfuel,True
25,C026,P0203,@chloe99,meh,NaN,glowly,True
26,C027,P0005,@hana,"great quality, fast delivery",£8,homenest,True
27,C028,P0200,@ben.t,This price is a steal!,NaN,homenest,True
28,C029,P0181,@ella.r,Price is too high tbh,"$1,050.00",homenest,True
29,C030,P0257,@ella.r,obsessed with this #glow #skincare,$45,snackbox,True
30,C031,P0180,@hana,NaN,NaN,homenest,False
31,C032,P0035,@anna_k,"delivery took 3 weeks, not happy",$120,snackbox,True
32,C033,P0088,@gabi_x,NaN,NaN,snackbox,False
33,C034,P0106,@anna_k,Best purchase this year,NaN,glowly,True
34,C035,P0159,@finn,Is this vegan?,$12.99,snackbox,True
35,C036,P0183,@hana,love love love,$12.99,glowly,True
36,C037,P0083,@finn,"Need a refund, arrived broken",NaN,homenest,True
37,C038,P0114,@anna_k,Refund please. Wrong size.,NaN,glowly,True
38,C039,P0201,@dev_m,Is this vegan?,NaN,homenest,True
39,C040,P0269,@ella.r,NaN,NaN,homenest,False