In [20]:
import pandas as pd
posts = pd.read_csv("../data/social_posts.csv")

In [21]:
posts.head()          # first 5 rows (head(10) for 10)
posts.tail(3)         # last 3 rows
posts.shape           # (rows, columns)   ← attribute, no ()
posts.columns         # the column names
posts.info()          # columns, types, and how many NON-missing values each has
posts.describe()      # stats for every number column: count, mean, std, min, quartiles, max

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   post_id         300 non-null    str
 1   date            300 non-null    str
 2   platform        300 non-null    str
 3   brand           300 non-null    str
 4   post_type       300 non-null    str
 5   followers       300 non-null    int64
 6   likes           300 non-null    int64
 7   comments        290 non-null    float64
 8   shares          290 non-null    float64
 9   sponsored       300 non-null    bool
 10  caption_length  300 non-null    int64
dtypes: bool(1), float64(2), int64(3), str(5)
memory usage: 34.5 KB

           followers         likes    comments      shares  caption_length
count     300.000000    300.000000  290.000000  290.000000      300.000000
mean    67628.526667   1354.946667   54.624138   25.313793      205.256667
std     33578.988435   1608.047017   69.011108   33.991676      110.986896
min     26207.000000     31.000000    1.000000    0.000000       22.000000
25%     41044.750000    388.750000   14.250000    6.000000      107.000000
50%     63805.500000    883.500000   33.000000   15.000000      201.000000
75%     87264.000000   1638.000000   66.750000   32.000000      300.250000
max    125918.000000  13577.000000  617.000000  261.000000      399.000000

In [22]:
posts.isna().sum()

post_id            0
date               0
platform           0
brand              0
post_type          0
followers          0
likes              0
comments          10
shares            10
sponsored          0
caption_length     0
dtype: int64

In [23]:
posts["likes"]                  # ONE column      → a Series
posts[["likes", "comments"]]   
# NaN spreads: 5 + NaN gives NaN. If any part of a row is missing, a + across columns gives NaN for that row.
# SEVERAL columns → a DataFrame (note the DOUBLE brackets)

     likes  comments
0      631      34.0
1      485      12.0
2     3158      88.0
3     1612      75.0
4     1387      70.0
..     ...       ...
295    234       7.0
296    188       6.0
297    321      17.0
298   4107     138.0
299   1990      66.0

[300 rows x 2 columns]

In [24]:
# posts["likes"].mean()      .median()   .max()   .min()   .sum()   .std()

posts["platform"].value_counts()                  # how many of each category
posts["platform"].value_counts(normalize=True)    # as PROPORTIONS instead of counts
posts["platform"].unique()                        # the distinct values
posts["platform"].nunique()                       # HOW MANY distinct values

# Missing values are NaN (“Not a Number”). NaN is technically a float, so one missing value turns a whole column of ints into floats. It’s the same idea as one string turning a NumPy array into strings.

3

In [25]:
# df["salary"] + 5000                      # a new Series, nothing saved
# df["bonus"] = df["salary"] * 0.10        # creates a NEW column, saved in df

In [26]:
# df.sort_values("salary", ascending=False)          # highest first
# df.sort_values("salary", ascending=False).head(2)  # top 2

In [27]:
# Summing across columns while skipping NaN-- having NaN makes whole col sum NaN
posts[["likes", "comments", "shares"]].sum(axis=1)    # axis=1 = across each row (2.2!), skips NaN

0       681.0
1       509.0
2      3298.0
3      1714.0
4      1472.0
        ...
295     247.0
296     196.0
297     340.0
298    4358.0
299    2113.0
Length: 300, dtype: float64

In [28]:
df = pd.DataFrame({
    "name":   ["Ali", "Sara", "Omar", "Hina"],
    "dept":   ["Sales", "Tech", "Sales", "HR"],
    "salary": [50000, 72000, 61000, 45000],
})

# A1: (4,3)
print(df.shape)

# A2: [name, dept, salary]
print(list(df.columns))

# A3: which type is each?: pd.Series, pd.DataFrame  
print(type(df["salary"]), type(df[["salary"]]))

# A4: 57000.0
print(df["salary"].mean())

# A5: Sales: 2, Tech: 1, HR: 1
print(df["dept"].value_counts())

# A6: 3
print(df["dept"].nunique())

# A7: [55000, 77000, 66000, 50000]
print(df["salary"] + 5000)

# A8: whose row comes first?: Sara
print(df.sort_values("salary", ascending=False).head(1))

# A9: (4,4)
df["bonus"] = df["salary"] * 0.1
print(df.shape)

# A10: what dtype, and what sum?: float, NaN--one nan makes the whole col float
s = pd.Series([1, None, 3])
print(s.dtype, s.sum())

# A11: which error type? (own cell): KeyError: case-sensitive
# df["Salary"]

(4, 3)
['name', 'dept', 'salary']
<class 'pandas.Series'> <class 'pandas.DataFrame'>
57000.0
dept
Sales    2
Tech     1
HR       1
Name: count, dtype: int64
3
0    55000
1    77000
2    66000
3    50000
Name: salary, dtype: int64
   name  dept  salary
1  Sara  Tech   72000
(4, 4)
float64 4.0

In [29]:
#b1
df= pd.read_csv("../data/social_posts.csv")
print(
df.shape,
df.head(5),
df.tail(3),
df.columns
)

(300, 11)   post_id        date   platform     brand post_type  followers  likes  \
0   P0001  2026-01-01  Instagram    Glowly     image      82837    631
1   P0002  2026-01-02     TikTok  HomeNest     image      27506    485
2   P0003  2026-01-02  Instagram   FitFuel     video      61341   3158
3   P0004  2026-01-03  Instagram  SnackBox     image     118210   1612
4   P0005  2026-01-04     TikTok  SnackBox     image     122826   1387

   comments  shares  sponsored  caption_length
0      34.0    16.0      False             158
1      12.0    12.0      False             311
2      88.0    52.0      False             277
3      75.0    27.0      False             236
4      70.0    15.0      False             121       post_id        date   platform     brand post_type  followers  likes  \
297   P0298  2026-06-29  Instagram  HomeNest  carousel      26263    321
298   P0299  2026-06-29     TikTok  SnackBox     image     125910   4107
299   P0300  2026-06-29     TikTok   FitFuel     image      61646   1990

     comments  shares  sponsored  caption_length
297      17.0     2.0      False             298
298     138.0   113.0       True             171
299      66.0    57.0       True             162   Index(['post_id', 'date', 'platform', 'brand', 'post_type', 'followers',
       'likes', 'comments', 'shares', 'sponsored', 'caption_length'],
      dtype='str')

In [30]:
#b2
print(
df.info(),
df.isna().sum()
)
#comments and shares have 10 missing vals each, confirmed
#float because they have NaNs-- even one NaN can make column float, likes has no missing vals

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   post_id         300 non-null    str
 1   date            300 non-null    str
 2   platform        300 non-null    str
 3   brand           300 non-null    str
 4   post_type       300 non-null    str
 5   followers       300 non-null    int64
 6   likes           300 non-null    int64
 7   comments        290 non-null    float64
 8   shares          290 non-null    float64
 9   sponsored       300 non-null    bool
 10  caption_length  300 non-null    int64
dtypes: bool(1), float64(2), int64(3), str(5)
memory usage: 34.5 KB
None post_id            0
date               0
platform           0
brand              0
post_type          0
followers          0
likes              0
comments          10
shares            10
sponsored          0
caption_length     0
dtype: int64

In [31]:
#b3
df.describe()
#likes-- mean: 1354.94, median: 883.50
#means are affected by outliers, not median

           followers         likes    comments      shares  caption_length
count     300.000000    300.000000  290.000000  290.000000      300.000000
mean    67628.526667   1354.946667   54.624138   25.313793      205.256667
std     33578.988435   1608.047017   69.011108   33.991676      110.986896
min     26207.000000     31.000000    1.000000    0.000000       22.000000
25%     41044.750000    388.750000   14.250000    6.000000      107.000000
50%     63805.500000    883.500000   33.000000   15.000000      201.000000
75%     87264.000000   1638.000000   66.750000   32.000000      300.250000
max    125918.000000  13577.000000  617.000000  261.000000      399.000000

In [32]:
#b4
print(
df["platform"].value_counts(),
df["platform"].value_counts(normalize=True),
df["brand"].nunique(),
df["post_type"].unique()
)

platform
Instagram    132
TikTok       104
Facebook      64
Name: count, dtype: int64 platform
Instagram    0.440000
TikTok       0.346667
Facebook     0.213333
Name: proportion, dtype: float64 5 <ArrowStringArray>
['image', 'video', 'carousel']
Length: 3, dtype: str

In [33]:
#b5
df["sponsored"].value_counts(normalize=True) *100

sponsored
False    75.666667
True     24.333333
Name: proportion, dtype: float64

In [34]:
#b6
likes= df["likes"]
comments= df["comments"]
shares= df["shares"]

total= df["engagement"] = likes + comments + shares
nans= df["engagement"].isna().sum()
total2= df[["likes" , "comments" , "shares"]].sum(axis=1)
nans2= total2.isna().sum()

nans, nans2

#.sum approach is better because it assumes NaNs as 0 and performs the actual sum, while adding normally makes the whole row nan even if only one col is missing a number

(np.int64(19), np.int64(0))

In [35]:
#b7
shortened= df[["post_id", "brand", 'platform', 'post_type' , 'likes']]
shortened.sort_values("likes", ascending=False).head(5)  # top 2

    post_id     brand   platform post_type  likes
18    P0019  SnackBox     TikTok     video  13577
102   P0103  SnackBox     TikTok  carousel  12052
128   P0129  SnackBox     TikTok     video   9030
276   P0277  SnackBox  Instagram     image   6133
209   P0210    Glowly     TikTok     video   5761

In [36]:
#b8
import numpy as np
df["engagement"]= df[["likes" , "comments" , "shares"]].sum(axis=1)
df['eng_rate']= (df['engagement']/df['followers'])*100
np.round(df['eng_rate'].mean(), 2)

np.float64(2.04)

In [38]:
#b9
print(
df['date'].min(), df['date'].max()
)

2026-01-01 2026-06-29

In [48]:
df["post_type"].value_counts(normalize=True)
np.round(df["likes"].mean(), 1)

sorted_engagement= df[["post_id", 'brand' , 'eng_rate']].sort_values("eng_rate", ascending=False)
sorted_engagement.head(3)

    post_id        brand   eng_rate
18    P0019     SnackBox  11.369844
102   P0103     SnackBox  11.092313
250   P0251  UrbanThread   8.540725

s = pd.Series([10, None, 20])
print(s.sum(), s.mean(), (s + 5).isna().sum())

The mean is 15.0, not 10.0. .mean() skips NaN in the count as well as the sum, so it’s 30 / 2 values = 15. You divided by 3. 
The isna count is 1, not 0. + doesn’t skip NaN, so s + 5 = [15, NaN, 25]. NaN + 5 is still NaN, and that gives 1 missing.